name: Format

on: [pull_request]

jobs:
    format:
        name: Stylua
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: JohnnyMorganz/stylua-action@v2
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
              # CLI arguments
              args: --check lua/ --config-path=.stylua.toml
