name: Lint

on: [pull_request]

jobs:
    lint:
        name: Luacheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Luacheck linter
              uses: lunarmodules/luacheck@v1
              with:
                  args: lua/ --globals vim Snacks
