name: Spec

on: [pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            url: https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.tar.gz
            manager: sudo apt-get
            packages: -y ripgrep
          - os: ubuntu-22.04
            url: https://github.com/neovim/neovim/releases/download/v0.9.0/nvim-linux64.tar.gz
            manager: sudo apt-get
            packages: -y ripgrep
          - os: ubuntu-22.04
            url: https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz
            manager: sudo apt-get
            packages: -y ripgrep
    steps:
      - uses: actions/checkout@v4
      - run: date +%F > todays-date
      - name: Restore from todays cache
        uses: actions/cache@v4
        with:
          path: _neovim
          key: ${{ runner.os }}-${{ matrix.url }}-${{ hashFiles('todays-date') }}

      - name: Prepare
        run: |
          sudo update-ca-certificates
          ${{ matrix.manager }} update
          ${{ matrix.manager }} install ${{ matrix.packages }}
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL ${{ matrix.url }} | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test

